name: xfads
channels:
  - anaconda
  - defaults
dependencies:
  - appnope=0.1.2
  - asttokens=2.0.5
  - backcall=0.2.0
  - blas=1.0
  - ca-certificates=2024.3.11
  - cffi=1.16.0
  - comm=0.1.2
  - debugpy=1.6.7
  - decorator=5.1.1
  - exceptiongroup=1.0.4
  - executing=0.8.3
  - gmp=6.2.1
  - gmpy2=2.1.2
  - importlib-metadata=6.0.0
  - importlib_metadata=6.0.0
  - ipykernel=6.25.0
  - ipython=8.15.0
  - jedi=0.18.1
  - jinja2=3.1.3
  - jupyter_client=8.6.0
  - jupyter_core=5.5.0
  - libcxx=14.0.6
  - libffi=3.4.4
  - libgfortran=5.0.0
  - libgfortran5=11.3.0
  - libopenblas=0.3.21
  - libprotobuf=3.20.3
  - libsodium=1.0.18
  - libuv=1.44.2
  - llvm-openmp=14.0.6
  - matplotlib-inline=0.1.6
  - mpc=1.1.0
  - mpfr=4.0.2
  - mpmath=1.3.0
  - ncurses=6.4
  - nest-asyncio=1.5.6
  - ninja=1.10.2
  - ninja-base=1.10.2
  - numpy=1.26.4
  - numpy-base=1.26.4
  - openssl=3.0.13
  - parso=0.8.3
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=23.3.1
  - platformdirs=3.10.0
  - prompt-toolkit=3.0.36
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pycparser=2.21
  - pygments=2.15.1
  - python=3.9.19
  - pytorch=2.2.0
  - pytorch-cpu=2.2.0
  - pyzmq=25.1.0
  - readline=8.2
  - setuptools=68.2.2
  - six=1.16.0
  - sleef=3.5.1
  - sqlite=3.45.3
  - stack_data=0.2.0
  - sympy=1.12
  - tk=8.6.12
  - tornado=6.3.3
  - traitlets=5.7.1
  - wcwidth=0.2.5
  - wheel=0.41.2
  - xz=5.4.6
  - zeromq=4.3.4
  - zlib=1.2.13
  - pip:
      - aiobotocore==2.13.1
      - aiohttp==3.9.5
      - aioitertools==0.11.0
      - aiosignal==1.3.1
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - arrow==1.3.0
      - asciitree==0.3.3
      - async-timeout==4.0.3
      - attrs==23.2.0
      - backports-tarfile==1.2.0
      - bidsschematools==0.7.2
      - blessed==1.20.0
      - botocore==1.34.131
      - certifi==2024.6.2
      - charset-normalizer==3.3.2
      - ci-info==0.3.0
      - click==8.1.7
      - click-didyoumean==0.3.1
      - contourpy==1.2.1
      - cycler==0.12.1
      - dandi==0.62.2
      - dandischema==0.10.1
      - dnspython==2.6.1
      - einops==0.8.0
      - email-validator==2.2.0
      - etelemetry==0.3.1
      - fasteners==0.19
      - filelock==3.14.0
      - fonttools==4.51.0
      - fqdn==1.5.1
      - frozenlist==1.4.1
      - fscacher==0.4.1
      - fsspec==2024.6.1
      - h5py==3.11.0
      - hdmf==3.14.1
      - humanize==4.9.0
      - hydra-core==1.3.2
      - idna==3.7
      - imageio==2.34.2
      - importlib-resources==6.4.0
      - install==1.3.5
      - interleave==0.2.1
      - isodate==0.6.1
      - isoduration==20.11.0
      - jaraco-classes==3.4.0
      - jaraco-context==5.3.0
      - jaraco-functools==4.0.1
      - jmespath==1.0.1
      - joblib==1.4.0
      - jsonpointer==3.0.0
      - jsonschema==4.22.0
      - jsonschema-specifications==2023.12.1
      - keyring==25.2.1
      - keyrings-alt==5.0.1
      - kiwisolver==1.4.5
      - lightning-utilities==0.11.2
      - markupsafe==2.1.5
      - matplotlib==3.8.4
      - more-itertools==10.3.0
      - multidict==6.0.5
      - natsort==8.4.0
      - networkx==3.2.1
      - nlb-tools==0.0.3
      - numcodecs==0.12.1
      - nwbinspector==0.4.37
      - omegaconf==2.3.0
      - opencv-python==4.10.0.84
      - packaging==24.0
      - pandas==1.3.4
      - pillow==10.3.0
      - pycryptodomex==3.20.0
      - pydantic==2.7.4
      - pydantic-core==2.18.4
      - pynwb==2.8.0
      - pyout==0.7.3
      - pyparsing==3.1.2
      - pyrecorder==0.2.1
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.0.1
      - pytorch-lightning==2.3.1
      - pytz==2024.1
      - pyyaml==6.0.1
      - referencing==0.35.1
      - requests==2.32.3
      - rfc3339-validator==0.1.4
      - rfc3987==1.3.8
      - rpds-py==0.18.1
      - ruamel-yaml==0.18.6
      - ruamel-yaml-clib==0.2.8
      - s3fs==2024.6.1
      - scikit-learn==1.4.2
      - scipy==1.13.0
      - seaborn==0.13.2
      - semantic-version==2.10.0
      - tenacity==8.4.2
      - threadpoolctl==3.5.0
      - torchmetrics==1.3.2
      - tqdm==4.66.2
      - types-python-dateutil==2.9.0.20240316
      - typing-extensions==4.11.0
      - tzdata==2024.1
      - uri-template==1.3.0
      - urllib3==1.26.19
      - webcolors==24.6.0
      - wrapt==1.16.0
      - xfads==0.5.0
      - yarl==1.9.4
      - zarr==2.18.2
      - zarr-checksum==0.4.0
      - zipp==3.18.1
